name: TodoTemplate CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:

  build-blazor-server:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/global.json

    - name: Restore dependencies
      run: dotnet restore src/Client/Web/TodoTemplateDevOps.Client.Web.csproj
      
    - name: Build
      run: dotnet build --no-restore src/Client/Web/TodoTemplateDevOps.Client.Web.csproj
